=== ritam099/wsd-lab/lab4/payment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" elementFormDefault="qualified" attributeFormDefault="unqualified" 
targetNamespace="http://www.example.com/payment" xmlns:payment="http://www.example.com/payment">

    <!-- Restriction for amount -->
    <xs:simpleType name="amountType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
            <xs:maxExclusive value="10000"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Restriction for card numbers -->
    <xs:simpleType name="cardNumberType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{16}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="transactionType">
        <xs:sequence>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="amount" type="payment:amountType"/>
            <xs:element name="currency" type="xs:string"/>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="status" type="xs:string"/>
            <xs:element name="cardNumber" type="payment:cardNumberType"/>
            <xs:element name="expiryDate" type="xs:gYearMonth"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>

    <xs:element name="transactions" type="payment:transactionListType"/>

    <xs:complexType name="transactionListType">
        <xs:sequence>
            <xs:element name="transaction" type="payment:transactionType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ritam099/wsd-lab/lab4/transaction.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="payment.xsl" type="text/xsl" ?>
<payment:transactions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:payment="http://www.example.com/payment" xsi:schemaLocation="http://www.example.com/payment payment.xsd">
    <payment:transaction id="t1">
        <payment:username>AaravSharma01</payment:username>
        <payment:amount>1200.50</payment:amount>
        <payment:currency>INR</payment:currency>
        <payment:date>2024-08-11</payment:date>
        <payment:status>Completed</payment:status>
        <payment:cardNumber>4111111111111111</payment:cardNumber>
        <payment:expiryDate>2026-05</payment:expiryDate>
    </payment:transaction>
    <payment:transaction id="t2">
        <payment:username>IshaPatel89</payment:username>
        <payment:amount>750.00</payment:amount>
        <payment:currency>INR</payment:currency>
        <payment:date>2024-08-10</payment:date>
        <payment:status>Pending</payment:status>
        <payment:cardNumber>5555555555554444</payment:cardNumber>
        <payment:expiryDate>2025-07</payment:expiryDate>
    </payment:transaction>
    <payment:transaction id="t3">
        <payment:username>RohitVerma77</payment:username>
        <payment:amount>3500.25</payment:amount>
        <payment:currency>INR</payment:currency>
        <payment:date>2024-08-09</payment:date>
        <payment:status>Completed</payment:status>
        <payment:cardNumber>6011000990139424</payment:cardNumber>
        <payment:expiryDate>2024-09</payment:expiryDate>
    </payment:transaction>
    <payment:transaction id="t4">
        <payment:username>AnikaMehta55</payment:username>
        <payment:amount>2499.99</payment:amount>
        <payment:currency>INR</payment:currency>
        <payment:date>2024-08-08</payment:date>
        <payment:status>Failed</payment:status>
        <payment:cardNumber>3566002020360505</payment:cardNumber>
        <payment:expiryDate>2023-12</payment:expiryDate>
    </payment:transaction>
    <payment:transaction id="t5">
        <payment:username>KabirSingh23</payment:username>
        <payment:amount>500.00</payment:amount>
        <payment:currency>INR</payment:currency>
        <payment:date>2024-08-07</payment:date>
        <payment:status>Completed</payment:status>
        <payment:cardNumber>4532756279624064</payment:cardNumber>
        <payment:expiryDate>2025-04</payment:expiryDate>
    </payment:transaction>
    <payment:transaction id="t6">
        <payment:username>PriyaGupta88</payment:username>
        <payment:amount>1850.75</payment:amount>
        <payment:currency>INR</payment:currency>
        <payment:date>2024-08-06</payment:date>
        <payment:status>Pending</payment:status>
        <payment:cardNumber>374111111111111</payment:cardNumber>
        <payment:expiryDate>2024-10</payment:expiryDate>
    </payment:transaction>
    <payment:transaction id="t7">
        <payment:username>VikramRao67</payment:username>
        <payment:amount>2999.99</payment:amount>
        <payment:currency>INR</payment:currency>
        <payment:date>2024-08-05</payment:date>
        <payment:status>Completed</payment:status>
        <payment:cardNumber>301111111111111</payment:cardNumber>
        <payment:expiryDate>2026-02</payment:expiryDate>
    </payment:transaction>
    <payment:transaction id="t8">
        <payment:username>NishaKumar99</payment:username>
        <payment:amount>999.50</payment:amount>
        <payment:currency>INR</payment:currency>
        <payment:date>2024-08-04</payment:date>
        <payment:status>Failed</payment:status>
        <payment:cardNumber>6011000990139424</payment:cardNumber>
        <payment:expiryDate>2025-11</payment:expiryDate>
    </payment:transaction>
</payment:transactions>
